[platformio]
default_envs = tx

; ==================================================
; TX
; ==================================================

[env:tx]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_src_filter =
  +<*>
  -<ESP32_FISK_RX/*>
  -<ESP32_FJARIL_RX/*>

build_unflags = -std=gnu++11

build_flags =
  -std=gnu++17

lib_deps =
  https://github.com/sparkfun/SparkFun_Qwiic_OLED_Arduino_Library.git
  someweisguy/esp_dmx@^4.1.0


; ==================================================
; RX FISK - ESP32-S3
; ==================================================

[env:rx_fisk]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

build_src_filter =
  +<ESP32_FISK_RX/*>

lib_deps =
  madhephaestus/ESP32Servo@^3.0.6


; ==================================================
; RX FJÄRIL - ESP32
; ==================================================

[env:rx_fjaril]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

build_src_filter =
  +<ESP32_FJARIL_RX/*>

lib_deps =
  madhephaestus/ESP32Servo@^3.0.6
  adafruit/Adafruit NeoPixel