[platformio]
default_envs = tx

[env:tx]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<*>
  -<ESP32_SERVO_RX/*>

build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17

lib_deps =
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit SH110X@^2.1.10
  someweisguy/esp_dmx@^4.1.0

[env:rx]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

build_src_filter =
  +<ESP32_SERVO_RX/*>

lib_deps =
  madhephaestus/ESP32Servo@^3.0.6